baseURL = "https://stephen-zulauf.github.io/behovadotnet/"
theme = "PaperMod"

# Enable to get proper Mathjax support
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


